# Используем официальный образ jrottenberg/ffmpeg (Alpine-версия)
FROM jrottenberg/ffmpeg:5.1-alpine

# Устанавливаем рабочую директорию
WORKDIR /data

# Создаем папки для входных и выходных данных
RUN mkdir -p /app/input 
RUN mkdir -p /app/output